server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FrancoPesenda/FinalBack
          default-label: main
          search-paths: config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0